version: 2
updates:

  - package-ecosystem: "python"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "python"
    directory: "/abc"
    schedule:
      interval: "daily"

  - package-ecosystem: "python"
    directory: "/jkl"
    schedule:
      interval: "daily"
